// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `authors` table.
    ///
    /// (Automatically generated by Diesel.)
    authors (id) {
        /// The `id` column of the `authors` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `first_name` column of the `authors` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        first_name -> Text,
        /// The `middle_name` column of the `authors` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        middle_name -> Nullable<Text>,
        /// The `second_name` column of the `authors` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        second_name -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `bookmarks` table.
    ///
    /// (Automatically generated by Diesel.)
    bookmarks (id) {
        /// The `id` column of the `bookmarks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `book_id` column of the `bookmarks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        book_id -> Binary,
        /// The `page` column of the `bookmarks` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        page -> SmallInt,
        /// The `title` column of the `bookmarks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `note` column of the `bookmarks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        note -> Nullable<Text>,
        /// The `owner_id` column of the `bookmarks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `books` table.
    ///
    /// (Automatically generated by Diesel.)
    books (id) {
        /// The `id` column of the `books` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `storage_id` column of the `books` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        storage_id -> Binary,
        /// The `title` column of the `books` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `path` column of the `books` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `uploader_id` column of the `books` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        uploader_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `books_authors` table.
    ///
    /// (Automatically generated by Diesel.)
    books_authors (book_id, author_id) {
        /// The `book_id` column of the `books_authors` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        book_id -> Binary,
        /// The `author_id` column of the `books_authors` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        author_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `books_tags` table.
    ///
    /// (Automatically generated by Diesel.)
    books_tags (book_id, tag_id) {
        /// The `book_id` column of the `books_tags` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        book_id -> Binary,
        /// The `tag_id` column of the `books_tags` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        tag_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `highlights` table.
    ///
    /// (Automatically generated by Diesel.)
    highlights (id) {
        /// The `id` column of the `highlights` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `book_id` column of the `highlights` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        book_id -> Binary,
        /// The `page` column of the `highlights` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        page -> SmallInt,
        /// The `start` column of the `highlights` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        start -> SmallInt,
        /// The `end` column of the `highlights` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        end -> SmallInt,
        /// The `title` column of the `highlights` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `note` column of the `highlights` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        note -> Nullable<Text>,
        /// The `owner_id` column of the `highlights` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `storages` table.
    ///
    /// (Automatically generated by Diesel.)
    storages (id) {
        /// The `id` column of the `storages` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `name` column of the `storages` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `settings` column of the `storages` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        settings -> Text,
    }
}

diesel::table! {
    /// Representation of the `tags` table.
    ///
    /// (Automatically generated by Diesel.)
    tags (id) {
        /// The `id` column of the `tags` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `name` column of the `tags` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `login` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        login -> Text,
        /// The `password` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Text,
        /// The `role` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        role -> Text,
    }
}

diesel::joinable!(bookmarks -> books (book_id));
diesel::joinable!(bookmarks -> users (owner_id));
diesel::joinable!(books -> storages (storage_id));
diesel::joinable!(books -> users (uploader_id));
diesel::joinable!(books_authors -> books (book_id));
diesel::joinable!(books_tags -> books (book_id));
diesel::joinable!(books_tags -> tags (tag_id));
diesel::joinable!(highlights -> books (book_id));
diesel::joinable!(highlights -> users (owner_id));

diesel::allow_tables_to_appear_in_same_query!(
    authors,
    bookmarks,
    books,
    books_authors,
    books_tags,
    highlights,
    storages,
    tags,
    users,
);
