name: UI

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/ui.yml"
      - "ui/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - ".github/workflows/ui.yml"
      - "ui/**"

env:
  WORKFLOW_NODE_VERSION: v16.x

defaults:
    run:
      working-directory: ./ui

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.WORKFLOW_NODE_VERSION }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
