//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::book::Entity as Book;
pub use super::shelf::Entity as Shelf;
pub use super::storage::Entity as Storage;
pub use super::user::Entity as User;
